baseURL = "https://midori-osteopathic-clinic.netlify.com/"
languageCode = "en-us"
title = "みどり接骨院"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "当院について"
        url     = "#about"
        weight  = 2
    [[menu.nav]]
        name    = "スタッフ"
        url     = "#profile"
        weight  = 3
    # [[menu.nav]]
    #     name    = "施術費用"
    #     url     = "#cost"
    #     weight  = 4
    [[menu.nav]]
        name    = "アクセス"
        url     = "#access"
        weight  = 5
    # [[menu.nav]]
    #     name    = "診察予約"
    #     url     = "#reservartion"
    #     weight  = 6

# Site Params
[params]
    home = "ホーム"
    # make logo at https://www.777logos.com/account/logos/concept/9270687/
    logo = "image/logo.png"
    # make telephone logo at https://www.777logos.com/account/logos/concept/9270714/
    phone = "image/phone.png"
    dateFormat = "1 April 2019"
    # Meta data
    description = "Home page of midori osteopathic clinic"
    author = "Yuusuke Takizawa"
    # Google Analitycs
    googleAnalitycsID = "Your ID"

    # headline Section
    [params.headline]
        enable  = true
        bgImage = "image/bg-headline.png"
        welcome = "image/home/welcome.png"
        description = ""

    # about Section
    [params.about]
        enable  = true
        image1 = "image/image/1.jpg"
        image2 = "image/image/2.jpg"
        image3 = "image/image/3.jpg"
        image4 = "image/image/4.jpg"
        image5 = "image/image/5.jpg"
        coupon = "image/coupon.png"
        description = ""

    # profile Section
    [params.profile]
        enable  = true
        ryu = "image/ryu.png" # 750*1000
        hiromi = "image/hiromi.png" # 750*1000
        description = ""

    # access Section
    [params.access]
        enable  = true
        nav1 = "image/nav/1.jpg"
        nav2 = "image/nav/2.jpg"
        nav3 = "image/nav/3.jpg"
        nav4 = "image/nav/4.jpg"
        nav5 = "image/nav/5.jpg"
        arrow = "image/arrow.gif"
        description = ""
    