baseURL = "https://midori-osteopathic-clinic.netlify.com/"
languageCode = "en-us"
title = "みどり整骨院"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Site Menus
[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "当院について"
        url     = "#about"
        weight  = 1
    [[menu.nav]]
        name    = "患者様の声"
        url     = "#review"
        weight  = 2
    [[menu.nav]]
        name    = "スタッフ"
        url     = "#profile"
        weight  = 3
    # [[menu.nav]]
    #     name    = "施術費用"
    #     url     = "/cost"
    #     weight  = 4
    [[menu.nav]]
        name    = "アクセス"
        url     = "#access"
        weight  = 5
    # [[menu.nav]]
    #     name    = "診察予約"
    #     url     = "#reservartion"
    #     weight  = 6

# Site Params
[params]
    home = "ホーム"
    # make logo at https://www.777logos.com/account/logos/concept/9270687/
    logo = "images/logo.png"
    # make telephone logo at https://www.777logos.com/account/logos/concept/9270714/
    phone = "images/phone.png"
    dateFormat = "1 April 2019"
    # Meta data
    description = "Home page of midori osteopathic clinic"
    author = "Yuusuke Takizawa"
    # Google Analitycs
    googleAnalitycsID = "Your ID"

    # headline Section
    [params.headline]
        enable  = true
        welcome = "images/welcome.png"
        headlinePC = "images/headline-pc.png"
        headlineMobile = "images/headline-mobile.png"
        description = ""

    # review Section
    [params.review]
        enable  = true
        sheet1 = "images/review/sheet1.png"
        sheet2 = "images/review/sheet2.png"
        description = ""

    # recommend Section
    [params.recommend]
        enable  = true
        image = "images/recommend.png"
        arrow = "images/arrow.png"
        description = ""

    # about Section
    [params.about]
        enable  = true
        image1 = "images/image/1.jpg"
        image2 = "images/image/2.jpg"
        image3 = "images/image/3.jpg"
        image4 = "images/image/4.jpg"
        image5 = "images/image/5.jpg"
        coupon = "images/coupon.png"
        description = ""

    # offer Section
    [params.offer]
        enable  = true
        cost = "images/cost.png"
        phone = "images/phone-icon.png"
        line = "images/line.png"
        description = ""

    # profile Section
    [params.profile]
        enable  = true
        ryu = "images/profile/ryu.png" # 750*1000
        hiromi = "images/profile/hiromi.png" # 750*1000
        description = ""

    # access Section
    [params.access]
        enable  = true
        nav1 = "images/nav/1.jpg"
        nav2 = "images/nav/2.jpg"
        nav3 = "images/nav/3.jpg"
        nav4 = "images/nav/4.jpg"
        nav5 = "images/nav/5.jpg"
        arrow = "images/arrow.gif"
        description = ""
    